server:
  port: 9000
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/askrindo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.askrindo: DEBUG
    org.hibernate: ERROR
    org.springframework: INFO
